name: Python application

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12.5]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry
    - name: View poetry --help
      run: poetry --help

    - name: Install dependencies
      shell: bash
      run: poetry install

    - name: Set environment variables
      run: |
        echo "SECRET_KEY='django-insecure-#-69-2dm()%r3_tzi(h%7_#dezbpz0o3jn6ta8d__amg@n)n2p'" >> $GITHUB_ENV
        echo "DEBUG='1'" >> $GITHUB_ENV
        echo "DJANGO_ALLOWED_HOSTS='localhost 127.0.0.1'" >> $GITHUB_ENV

    - name: Test
      run: |
        poetry run python manage.py test
